[package]
name = "ms-todo-app"
version = "0.2.0"
edition = "2021"

[dependencies]
i18n-embed-fl = "0.9.4"
rust-embed = "8"
open = "5.0.2"
dirs = "6.0.0"
cli-clipboard = "0.4.0"
slotmap = "1.0.7"
ron = "0.10.1"
thiserror = "2.0.12"
tracing = "0.1.40"
anyhow = "1.0.99"
base64 = "0.22.1"
sha2 = "0.10.9"
rand = "0.9.2"
tiny_http = "0.12.0"
url = "2.5.4"
webbrowser = "1.0.5"
env_logger = "0.11.8"
serde_json = "1.0.143"
reqwest = { version = "0.12.23", features = ["blocking", "json"] }
keyring = "2.0"
license = { version= "3.7.0" , include = [
    "/license-list-data/json"
]}
[dependencies.tracing-subscriber]
version = "0.3.19"
features = ["env-filter"]

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
branch = "master" 
default-features = false
features = ["multi-window", "tokio", "winit", "about", "wgpu"]

[dependencies.i18n-embed]
version = "0.15.4"
features = ["fluent-system", "desktop-requester"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.sqlx]
version = "0.8.0"
features = ["sqlite"]
default-features = false

[dependencies.chrono]
version = "0.4.35"
features = ["serde"]

[dependencies.uuid]
version = "1.2.1"
features = ["v4"]

[features]
default = ["ms_graph"]
ms_graph = []
local_storage = []

[patch."https://github.com/smithay/client-toolkit.git"]
sctk = { package = "smithay-client-toolkit", version = "=0.19.2" }

# [patch."https://github.com/pop-os/libcosmic.git"]
# libcosmic = { path = "../../edfloreshz-ext/libcosmic" }
